### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by yechiel-optimalq** [aviramha/aioaerospike#14]
Hi aviram,

I wanted to ask a few questions before trying to utilize this repo:
1. Is it in active dev?
2. Did you had a chance to test performance? We tried a very simple async await implementation and can't say the performance similar to other clients (Go for example)
3. What is the "Design" / "architecture"? could you write in README so if we decide to contribute we will follow the architecture?

**Comment by aviramha** [comment]
Hey Yechiel,
1. I started this as a side project while my company decided we migrate to aerospike. We stopped migration quite early, so I had less interest to continue development.
2. No I hadn't a chance to test performance. I assume it will be faster in concurrency than other non async python implementations but might perform less better in cpu operations (which are minimal from what I saw) due to other libraries using C extension. I planned that after the library will be mature I'll write rust extension for protocol encoding like hiredis does for Redis.
3. You're more than welcome to contribute and join as a maintainer for this, as it's MIT you can also fork and it's fine by me. I'm not actively adding features but I can help with reviews and guidance. 

Please notice that I haven't done the "heavy" part of cluster awareness but from what I've checked it shouldn't be too hard. Aerospike protocol (compared to alternatives) is quite well structured and intuitive.

**Comment by yechiel-optimalq** [comment]
Did u give up on Aerospike or on Python? what did u decide to do eventually in your company?
if gave up on Aerospike, why and to what u moved to?

**Comment by aviramha** [comment]
We are using Redis and were almost switching to Aerospike. We decided that Aerospike migration might be an overkill for us. I think Aerospike is great, but moving from Redis to Aerospike takes a lot of resources.
